### ISSUE TITLE
Panic for simple path

### ISSUE THREAD

**Issue by axle-h** [shuoli84/poly2tri-rs#11]
Tried triangulating this:

![duck copy](https://github.com/shuoli84/poly2tri-rs/assets/4509102/d3b9b5ca-634a-4c84-836a-84e55b0564e0)

Simplified as an example:

```rust
use poly2tri_rs::{SweeperBuilder, Point};

fn main() {
    SweeperBuilder::new(vec![
        Point::new(244.0,0.0), Point::new(279.0,0.0), Point::new(296.0,3.0),
        Point::new(299.0,5.0), Point::new(315.0,9.0), Point::new(324.0,14.0),
        Point::new(327.0,14.0), Point::new(330.0,17.0), Point::new(333.0,17.0),
        Point::new(334.0,19.0), Point::new(338.0,20.0), Point::new(339.0,22.0),
        Point::new(347.0,26.0), Point::new(354.0,33.0), Point::new(356.0,33.0),
        Point::new(369.0,47.0), Point::new(378.0,63.0), Point::new(381.0,75.0),
        Point::new(381.0,82.0), Point::new(396.0,97.0), Point::new(396.0,99.0),
        Point::new(408.0,110.0), Point::new(408.0,112.0), Point::new(410.0,112.0),
        Point::new(415.0,118.0), Point::new(423.0,122.0), Point::new(459.0,122.0),
        Point::new(463.0,126.0), Point::new(467.0,135.0), Point::new(467.0,151.0),
        Point::new(464.0,155.0), Point::new(459.0,156.0), Point::new(457.0,158.0),
        Point::new(430.0,165.0), Point::new(376.0,174.0), Point::new(347.0,176.0),
        Point::new(339.0,183.0), Point::new(322.0,189.0), Point::new(329.0,197.0),
        Point::new(329.0,199.0), Point::new(332.0,201.0), Point::new(334.0,206.0),
        Point::new(337.0,208.0), Point::new(341.0,216.0), Point::new(343.0,217.0),
        Point::new(344.0,221.0), Point::new(351.0,230.0), Point::new(364.0,256.0),
        Point::new(372.0,285.0), Point::new(371.0,307.0), Point::new(357.0,341.0),
        Point::new(355.0,342.0), Point::new(354.0,346.0), Point::new(352.0,347.0),
        Point::new(348.0,355.0), Point::new(345.0,357.0), Point::new(345.0,359.0),
        Point::new(340.0,363.0), Point::new(340.0,365.0), Point::new(326.0,379.0),
        Point::new(324.0,379.0), Point::new(320.0,384.0), Point::new(318.0,384.0),
        Point::new(307.0,394.0), Point::new(305.0,394.0), Point::new(304.0,396.0),
        Point::new(297.0,399.0), Point::new(293.0,403.0), Point::new(287.0,405.0),
        Point::new(286.0,407.0), Point::new(276.0,412.0), Point::new(302.0,408.0),
        Point::new(319.0,408.0), Point::new(328.0,411.0), Point::new(331.0,417.0),
        Point::new(330.0,419.0), Point::new(324.0,421.0), Point::new(324.0,423.0),
        Point::new(328.0,427.0), Point::new(330.0,427.0), Point::new(334.0,432.0),
        Point::new(333.0,437.0), Point::new(329.0,441.0), Point::new(319.0,444.0),
        Point::new(304.0,445.0), Point::new(297.0,449.0), Point::new(292.0,456.0),
        Point::new(285.0,460.0), Point::new(261.0,461.0), Point::new(235.0,459.0),
        Point::new(232.0,462.0), Point::new(228.0,462.0), Point::new(228.0,464.0),
        Point::new(238.0,469.0), Point::new(238.0,478.0), Point::new(229.0,484.0),
        Point::new(209.0,488.0), Point::new(205.0,492.0), Point::new(205.0,494.0),
        Point::new(197.0,500.0), Point::new(144.0,500.0), Point::new(115.0,497.0),
        Point::new(95.0,493.0), Point::new(81.0,487.0), Point::new(78.0,484.0),
        Point::new(77.0,478.0), Point::new(88.0,456.0), Point::new(90.0,455.0),
        Point::new(97.0,441.0), Point::new(105.0,431.0), Point::new(106.0,426.0),
        Point::new(103.0,426.0), Point::new(97.0,422.0), Point::new(92.0,421.0),
        Point::new(91.0,419.0), Point::new(83.0,416.0), Point::new(82.0,414.0),
        Point::new(78.0,413.0), Point::new(70.0,406.0), Point::new(68.0,406.0),
        Point::new(66.0,403.0), Point::new(64.0,403.0), Point::new(48.0,388.0),
        Point::new(48.0,386.0), Point::new(43.0,382.0), Point::new(43.0,380.0),
        Point::new(37.0,373.0), Point::new(31.0,361.0), Point::new(26.0,344.0),
        Point::new(25.0,323.0), Point::new(23.0,320.0), Point::new(23.0,316.0),
        Point::new(3.0,262.0), Point::new(2.0,253.0), Point::new(0.0,249.0),
        Point::new(0.0,227.0), Point::new(3.0,220.0), Point::new(8.0,214.0),
        Point::new(19.0,209.0), Point::new(36.0,209.0), Point::new(46.0,211.0),
        Point::new(73.0,222.0), Point::new(80.0,216.0), Point::new(98.0,207.0),
        Point::new(130.0,198.0), Point::new(156.0,195.0), Point::new(184.0,195.0),
        Point::new(203.0,197.0), Point::new(203.0,189.0), Point::new(197.0,182.0),
        Point::new(197.0,180.0), Point::new(189.0,173.0), Point::new(187.0,173.0),
        Point::new(185.0,170.0), Point::new(183.0,170.0), Point::new(176.0,162.0),
        Point::new(174.0,162.0), Point::new(174.0,160.0), Point::new(172.0,160.0),
        Point::new(172.0,158.0), Point::new(162.0,148.0), Point::new(162.0,146.0),
        Point::new(156.0,139.0), Point::new(151.0,129.0), Point::new(146.0,112.0),
        Point::new(145.0,101.0), Point::new(147.0,81.0), Point::new(151.0,68.0),
        Point::new(159.0,52.0), Point::new(161.0,51.0), Point::new(165.0,43.0),
        Point::new(168.0,41.0), Point::new(168.0,39.0), Point::new(178.0,29.0),
        Point::new(180.0,29.0), Point::new(183.0,25.0), Point::new(185.0,25.0),
        Point::new(193.0,18.0), Point::new(210.0,9.0), Point::new(232.0,2.0),
        Point::new(244.0,1.0)
    ]).build().triangulate();
}
```

I get a panic:

```
thread 'main' panicked at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/advancing_front/vec_backed.rs:239:67:
called `Result::unwrap()` on an `Err` value: 19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1652:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/result.rs:1077:23
   4: poly2tri_rs::advancing_front::vec_backed::AdvancingFront::update_triangle
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/advancing_front/vec_backed.rs:239:19
   5: poly2tri_rs::sweeper::Sweeper::map_triangle_to_nodes
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:511:17
   6: poly2tri_rs::sweeper::Sweeper::legalize
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:436:13
   7: poly2tri_rs::sweeper::Sweeper::fill_one
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:567:9
   8: poly2tri_rs::sweeper::Sweeper::fill_right_concave_edge_event
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:849:19
   9: poly2tri_rs::sweeper::Sweeper::fill_right_convex_edge_event
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:894:13
  10: poly2tri_rs::sweeper::Sweeper::fill_right_below_edge_event
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:830:13
  11: poly2tri_rs::sweeper::Sweeper::fill_right_above_edge_event
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:802:17
  12: poly2tri_rs::sweeper::Sweeper::fill_edge_event
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:782:13
  13: poly2tri_rs::sweeper::Sweeper::edge_event
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:724:13
  14: poly2tri_rs::sweeper::Sweeper::sweep_points
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:220:17
  15: poly2tri_rs::sweeper::Sweeper::triangulate_with_observer
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:192:9
  16: poly2tri_rs::sweeper::Sweeper::triangulate
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poly2tri-rs-0.1.2/src/sweeper.rs:170:9
  17: keyboard_zoo::main
             at ./src/main.rs:18:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5

```

**Comment by axle-h** [comment]
Just had a go with the `poly2tri` crate and it triangulates it fine:

```rust
use poly2tri::{Polygon, CDT};

fn main() {
    let mut polygon = Polygon::new();
    polygon.add_point(244.0, 0.0);
    polygon.add_point(279.0, 0.0);
    polygon.add_point(296.0, 3.0);
    polygon.add_point(299.0, 5.0);
    polygon.add_point(315.0, 9.0);
    polygon.add_point(324.0, 14.0);
    polygon.add_point(327.0, 14.0);
    polygon.add_point(330.0, 17.0);
    polygon.add_point(333.0, 17.0);
    polygon.add_point(334.0, 19.0);
    polygon.add_point(338.0, 20.0);
    polygon.add_point(339.0, 22.0);
    polygon.add_point(347.0, 26.0);
    polygon.add_point(354.0, 33.0);
    polygon.add_point(356.0, 33.0);
    polygon.add_point(369.0, 47.0);
    polygon.add_point(378.0, 63.0);
    polygon.add_point(381.0, 75.0);
    polygon.add_point(381.0, 82.0);
    polygon.add_point(396.0, 97.0);
    polygon.add_point(396.0, 99.0);
    polygon.add_point(408.0, 110.0);
    polygon.add_point(408.0, 112.0);
    polygon.add_point(410.0, 112.0);
    polygon.add_point(415.0, 118.0);
    polygon.add_point(423.0, 122.0);
    polygon.add_point(459.0, 122.0);
    polygon.add_point(463.0, 126.0);
    polygon.add_point(467.0, 135.0);
    polygon.add_point(467.0, 151.0);
    polygon.add_point(464.0, 155.0);
    polygon.add_point(459.0, 156.0);
    polygon.add_point(457.0, 158.0);
    polygon.add_point(430.0, 165.0);
    polygon.add_point(376.0, 174.0);
    polygon.add_point(347.0, 176.0);
    polygon.add_point(339.0, 183.0);
    polygon.add_point(322.0, 189.0);
    polygon.add_point(329.0, 197.0);
    polygon.add_point(329.0, 199.0);
    polygon.add_point(332.0, 201.0);
    polygon.add_point(334.0, 206.0);
    polygon.add_point(337.0, 208.0);
    polygon.add_point(341.0, 216.0);
    polygon.add_point(343.0, 217.0);
    polygon.add_point(344.0, 221.0);
    polygon.add_point(351.0, 230.0);
    polygon.add_point(364.0, 256.0);
    polygon.add_point(372.0, 285.0);
    polygon.add_point(371.0, 307.0);
    polygon.add_point(357.0, 341.0);
    polygon.add_point(355.0, 342.0);
    polygon.add_point(354.0, 346.0);
    polygon.add_point(352.0, 347.0);
    polygon.add_point(348.0, 355.0);
    polygon.add_point(345.0, 357.0);
    polygon.add_point(345.0, 359.0);
    polygon.add_point(340.0, 363.0);
    polygon.add_point(340.0, 365.0);
    polygon.add_point(326.0, 379.0);
    polygon.add_point(324.0, 379.0);
    polygon.add_point(320.0, 384.0);
    polygon.add_point(318.0, 384.0);
    polygon.add_point(307.0, 394.0);
    polygon.add_point(305.0, 394.0);
    polygon.add_point(304.0, 396.0);
    polygon.add_point(297.0, 399.0);
    polygon.add_point(293.0, 403.0);
    polygon.add_point(287.0, 405.0);
    polygon.add_point(286.0, 407.0);
    polygon.add_point(276.0, 412.0);
    polygon.add_point(302.0, 408.0);
    polygon.add_point(319.0, 408.0);
    polygon.add_point(328.0, 411.0);
    polygon.add_point(331.0, 417.0);
    polygon.add_point(330.0, 419.0);
    polygon.add_point(324.0, 421.0);
    polygon.add_point(324.0, 423.0);
    polygon.add_point(328.0, 427.0);
    polygon.add_point(330.0, 427.0);
    polygon.add_point(334.0, 432.0);
    polygon.add_point(333.0, 437.0);
    polygon.add_point(329.0, 441.0);
    polygon.add_point(319.0, 444.0);
    polygon.add_point(304.0, 445.0);
    polygon.add_point(297.0, 449.0);
    polygon.add_point(292.0, 456.0);
    polygon.add_point(285.0, 460.0);
    polygon.add_point(261.0, 461.0);
    polygon.add_point(235.0, 459.0);
    polygon.add_point(232.0, 462.0);
    polygon.add_point(228.0, 462.0);
    polygon.add_point(228.0, 464.0);
    polygon.add_point(238.0, 469.0);
    polygon.add_point(238.0, 478.0);
    polygon.add_point(229.0, 484.0);
    polygon.add_point(209.0, 488.0);
    polygon.add_point(205.0, 492.0);
    polygon.add_point(205.0, 494.0);
    polygon.add_point(197.0, 500.0);
    polygon.add_point(144.0, 500.0);
    polygon.add_point(115.0, 497.0);
    polygon.add_point(95.0, 493.0);
    polygon.add_point(81.0, 487.0);
    polygon.add_point(78.0, 484.0);
    polygon.add_point(77.0, 478.0);
    polygon.add_point(88.0, 456.0);
    polygon.add_point(90.0, 455.0);
    polygon.add_point(97.0, 441.0);
    polygon.add_point(105.0, 431.0);
    polygon.add_point(106.0, 426.0);
    polygon.add_point(103.0, 426.0);
    polygon.add_point(97.0, 422.0);
    polygon.add_point(92.0, 421.0);
    polygon.add_point(91.0, 419.0);
    polygon.add_point(83.0, 416.0);
    polygon.add_point(82.0, 414.0);
    polygon.add_point(78.0, 413.0);
    polygon.add_point(70.0, 406.0);
    polygon.add_point(68.0, 406.0);
    polygon.add_point(66.0, 403.0);
    polygon.add_point(64.0, 403.0);
    polygon.add_point(48.0, 388.0);
    polygon.add_point(48.0, 386.0);
    polygon.add_point(43.0, 382.0);
    polygon.add_point(43.0, 380.0);
    polygon.add_point(37.0, 373.0);
    polygon.add_point(31.0, 361.0);
    polygon.add_point(26.0, 344.0);
    polygon.add_point(25.0, 323.0);
    polygon.add_point(23.0, 320.0);
    polygon.add_point(23.0, 316.0);
    polygon.add_point(3.0, 262.0);
    polygon.add_point(2.0, 253.0);
    polygon.add_point(0.0, 249.0);
    polygon.add_point(0.0, 227.0);
    polygon.add_point(3.0, 220.0);
    polygon.add_point(8.0, 214.0);
    polygon.add_point(19.0, 209.0);
    polygon.add_point(36.0, 209.0);
    polygon.add_point(46.0, 211.0);
    polygon.add_point(73.0, 222.0);
    polygon.add_point(80.0, 216.0);
    polygon.add_point(98.0, 207.0);
    polygon.add_point(130.0, 198.0);
    polygon.add_point(156.0, 195.0);
    polygon.add_point(184.0, 195.0);
    polygon.add_point(203.0, 197.0);
    polygon.add_point(203.0, 189.0);
    polygon.add_point(197.0, 182.0);
    polygon.add_point(197.0, 180.0);
    polygon.add_point(189.0, 173.0);
    polygon.add_point(187.0, 173.0);
    polygon.add_point(185.0, 170.0);
    polygon.add_point(183.0, 170.0);
    polygon.add_point(176.0, 162.0);
    polygon.add_point(174.0, 162.0);
    polygon.add_point(174.0, 160.0);
    polygon.add_point(172.0, 160.0);
    polygon.add_point(172.0, 158.0);
    polygon.add_point(162.0, 148.0);
    polygon.add_point(162.0, 146.0);
    polygon.add_point(156.0, 139.0);
    polygon.add_point(151.0, 129.0);
    polygon.add_point(146.0, 112.0);
    polygon.add_point(145.0, 101.0);
    polygon.add_point(147.0, 81.0);
    polygon.add_point(151.0, 68.0);
    polygon.add_point(159.0, 52.0);
    polygon.add_point(161.0, 51.0);
    polygon.add_point(165.0, 43.0);
    polygon.add_point(168.0, 41.0);
    polygon.add_point(168.0, 39.0);
    polygon.add_point(178.0, 29.0);
    polygon.add_point(180.0, 29.0);
    polygon.add_point(183.0, 25.0);
    polygon.add_point(185.0, 25.0);
    polygon.add_point(193.0, 18.0);
    polygon.add_point(210.0, 9.0);
    polygon.add_point(232.0, 2.0);
    polygon.add_point(244.0, 1.0);
    let cdt = CDT::new(polygon);
    let triangles = cdt.triangulate();
    println!("{}", triangles.size());
}
```

Output:

```
179
```
